version: '3.8'

services:
  opncht-server:
    build: .
    image: opncht-server
    tty: true
    ports:
      - '3030:3030'
    depends_on:
      - postgresdb
    volumes:
      - .:/usr/src/opncht-server
    networks:
      - opncht-network

  postgresdb:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    ports:
      - '5432:5432'
    volumes: 
      - dbdata:/var/lib/postgresql/data
    networks:
      - opncht-network

volumes:
  dbdata:
    driver: local

networks:
  opncht-network:
    driver: bridge
